namespace: newsify-dev
services:
  backend:
    containerName: newsify-backend
    image: nkwn/newsify-backend
    tag: latest-577bbb1
    port: 8080
    ingress:
      enabled: true
      host: dev.backend.id.vn
      path: "/api"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
  audio-service:
    containerName: audio-service
    image: nkwn/newsify-audio-service
    tag: latest-213f382
    port: 8000
    ingress:
      enabled: true
      host: dev.backend.id.vn
      path: "/audio"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
  trending-service:
    containerName: trending-service
    image: nkwn/newsify-trending-service
    tag: latest-8b1afce
    port: 8001
    ingress:
      enabled: true
      host: dev.backend.id.vn
      path: "/trending"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
replicaCount: 1
