namespace: newsify-dev
services:
  backend:
    containerName: newsify-backend
    image: nkwn/newsify-backend
    tag: dev-f2e9256
    port: 8080
    ingress:
      enabled: true
      host: dev.backend.id.vn
      path: /api(/|$)(.*)
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
  audio-service:
    containerName: audio-service
    image: nkwn/newsify-audio-service
    tag: latest-ece5fd2
    port: 8000
    ingress:
      enabled: true
      host: dev.backend.id.vn
      path: "/audio"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
  trending-service:
    containerName: trending-service
    image: nkwn/newsify-trending-service
    tag: latest-fd15924
    port: 8001
    ingress:
      enabled: true
      host: dev.backend.id.vn
      path: "/trending"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
  frontend:
    containerName: newsify-frontend
    image: nkwn/newsify-frontend
    tag: dev-750c64b
    port: 3000
    ingress:
      enabled: true
      host: dev.backend.id.vn
      path: "/"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
replicaCount: 1
