apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ntkwan/newsify.git
    path: ingress/dev
    targetRevision: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: newsify-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true