name: Backend Service CD

on:
  push:
    branches: [ main, dev, 'quan/feature/be/cd' ]

  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'backend/pnpm-lock.yaml'
      
      - name: Install dependencies
        working-directory: ./backend
        run: pnpm install
      
      - name: Build application
        working-directory: ./backend
        run: pnpm build
    
  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Determine image tag
        id: determine_tag
        run: |
          # Get short commit SHA
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Determine the tag based on branch
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            echo "tag=dev-${SHORT_SHA}" >> $GITHUB_OUTPUT
          else
            # For other branches (like quan/feature/be/cd), use branch name
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            SAFE_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/\//-/g')
            echo "tag=${SAFE_BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/newsify-backend:${{ steps.determine_tag.outputs.tag }}