name: Trending Service CD

on:
  push:
    branches: [ main, dev, 'quan/feature/be/cd' ]

  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'services/trending-service/requirements.txt'
      
      - name: Install dependencies
        working-directory: ./services/trending-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test uvicorn server launch
        working-directory: ./services/trending-service
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8001 &
          sleep 5
          curl -s http://localhost:8001/health || curl -s http://localhost:8001/ || true
          pkill -f uvicorn || true

  build-and-push:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Generate Docker tags
        id: meta
        run: |
          # Get short commit SHA
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Initialize tags array
          TAGS=""
          
          # Configure tags based on branch
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            TAGS="${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:latest"
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            TAGS="${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:dev-${SHORT_SHA}"
          else
            # For other branches, use branch name and SHA
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            SAFE_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/\//-/g')
            TAGS="${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:${SAFE_BRANCH_NAME}-${SHORT_SHA}"
          fi
          
          # Set output for build step
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/trending-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:buildcache,mode=max