name: Trending Service CD

on:
  push:
    branches: [ main, dev, 'quan/feature/be/cd' ]
    paths:
      - 'trending-service/**'
      - '.github/workflows/trending-service-cd.yml'
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service
          tags: |
            type=ref,event=branch
            type=sha,format=short
            latest
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./trending-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/newsify-trending-service:buildcache,mode=max